[package]
name = "tagscraper"
version = "0.6.0"
edition = "2021"

[dependencies]
audiotags = "0.4.1"
clap = { version = "4.4.18", features = ["derive"] }

[[bin]]
name = "tagscraper"
path = "src/main.rs"
