[package]
name = "tagscraper"
version = "0.5.0"
edition = "2021"

[dependencies]
audiotags = "0.4.1"
clap = { version = "4.3.11", features = ["derive"] }
itertools = "0.11.0"
walkdir = "2.3.3"

[[bin]]
name = "tagscraper"
path = "src/main.rs"
